### ISSUE TITLE
Integration with RDF.rb as a storage adapter

### ISSUE THREAD

**Issue by abargnesi** [cordawyn/redlander#11]
There is a great ecosystem of ruby libraries and tools in [RDF.rb](https://github.com/ruby-rdf/rdf) including RDF storage adapters (e.g. Mongo, DataObjects, AllegroGraph, etc.). This seems like a great opportunity to integrate redlander as an RDF storage adapter for Redland storage implementations.

Doing so would enable several storage implementations in Redland listed [here](http://librdf.org/docs/api/redland-storage-modules.html).

This seems like a natural "connect the dots" type of scenario, but I may be missing something. What do you think @cordawyn, @gkellogg?

**Comment by gkellogg** [comment]
It would be great to have more storage adaptors for RDF.rb, if someone were interested in doing this. It's pretty simple, just a couple of methods to implement. There's a somewhat dated description of implementing this [here](http://blog.datagraph.org/2010/04/rdf-repository-howto).

Basically, you implement core interfaces of [RDF::Repository](http://www.rubydoc.info/github/ruby-rdf/rdf/RDF/Repository), such as those in [RDF::Repository::Implementation](https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/repository.rb#L230-L457). This is centered around `#each_statement` and `#query_execute`, but it is often good to implement more accessors for better performance.

Note that the RDF::Raptor gem duplicates much of the functionality of Redlands for parsing/serializing, which tends to work well with the general architectural approach of RDF.rb.

**Comment by abargnesi** [comment]
This looks great. Is `#query_execute` the right method to override in implementations to handle SPARQL query input parsed from the _sparql_ gem?

**Comment by gkellogg** [comment]
`#query_execute` is the top-level thing implemented for native Repository querying. For the most part, BGP, but can also take some other pattern forms. Normally, I would expect you to query the repository using SPARQL::Client, rather than natively.

One thing we're looking at is to support a SPARQL Algebra to SPARQL Grammar transformation, which could be used in `#query_execute` to turn the query into a regular SPARQL query that can be handed to the query engine using some other mechanism (such as SPARQL::Client); but, that remains on the TODO list. (At the core, if you are using a RDF::Query, or RDF::Query::Pattern argument to `#query_pattern`, this can easily be turned into a simple SPARQL query).

**Comment by cordawyn** [comment]
I would like to add another vote for querying the repository using SPARQL rather than using "native" direct calls. But generally, I'm okay with using Redlander however you see fitting ;-)

However, I suspect that this may turn into a wrapper-in-a-wrapper thing, since the both projects use similar constructs for representing similar data (i.e. statements, nodes, etc.). Perhaps, you might consider using only FFI bindings from redlander (found in "redland.rb" file) to build an adapter for RDB.rb.

**Comment by abargnesi** [comment]
I'm referring to executing SPARQL queries in-process versus over the network. If the RDF store has support for this you could avoid the HTTP overhead.

@cordawyn Fully agree about the wrapper in wrapper thing. That would not be efficient or maintainable. Using the FFI descriptors in redland.rb could be a good starting point. I'm trying to integrate Apache Jena with RDF.rb at the moment ([rdf-jena](https://github.com/abargnesi/rdf-jena)), but will get back to this early next year.

Will close for now.
